liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # define your filter sets under this option
    filter_sets:

        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_product_thumbnail:

            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [300, 300]
                    mode:          inset
                    allow_upscale: true

                # create border by placing image on larger black background
                background:
                    size:     [300, 300]
                    position: center
                    color:    '#fff'


                watermark:

                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../public/image/water.png

                    # size of the water mark relative to the input image
                    size: 0.2

                    # set the position of the watermark
                    position: bottomleft

        squared_category_thumbnail:

                    # set your image quality defaults
                    jpeg_quality:          85
                    png_compression_level: 8

                    # setup the filter steps to apply for this transformation
                    filters:

                        # auto rotate the image using EXIF metadata
                        auto_rotate: ~

                        # strip the image of all metadata
                        strip: ~

                        # scale and square the image to the given dimensions
                        thumbnail:
                            size:          [80, 80]
                            mode:          inset
                            allow_upscale: true

                        # create border by placing image on larger black background
                        background:
                            size:     [80, 80]
                            position: center
                            color:    '#fff'